apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor-app-of-apps
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: https://github.com/org-sam/infra-gitops.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true