fullnameOverride: ecommerce-frontend

# replicaCount: 1

image:
  repository: saiwmon/ecommerce-frontend
  tag: latest
  pullPolicy: Always

container:
  name: ecommerce-frontend
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: alb

  commonAnnotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "60"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb

  annotations:
    alb.ingress.kubernetes.io/group.name: dev-eks

  hosts:
    - host: ecommerce.dev.platosedu.io
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"

env:
  NEXT_PUBLIC_CATALOG_SERVICE_URL: "http://ecommerce-catalog-service.ecommerce-catalog-service"
  NEXT_PUBLIC_ORDER_SERVICE_URL: "http://localhost:3002"
  OTEL_SERVICE_NAME: "ecommerce-frontend"

opentelemetry:
  enabled: true
  type: nodejs
  endpoint: "http://signoz-dev-demo-otel-collector.signoz.svc.cluster.local:4318"
