fullnameOverride: ecommerce-frontend

image:
  repository: saiwmon/ecommerce-frontend
  tag: v1.0.0  # This will be updated by manual promotion
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"

env:
  NEXT_PUBLIC_CATALOG_SERVICE_URL: "http://ecommerce-catalog-service.ecommerce-catalog-service"
  NEXT_PUBLIC_ORDER_SERVICE_URL: "http://localhost:3002"
  OTEL_SERVICE_NAME: "ecommerce-frontend"
  NODE_ENV: "production"

container:
  name: ecommerce-frontend
  port: 3000

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: alb

  commonAnnotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    kubernetes.io/ingress.class: alb

  annotations:
    alb.ingress.kubernetes.io/group.name: prod-demo
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:ACCOUNT_ID:certificate/CERT_ID"

  hosts:
    - host: ecommerce.mkt.posanhanguera.com.br
      paths:
        - path: /
          pathType: Prefix

istio:
  enabled: true
  gateway: "istio-system/shared-gateway"
  host: "ecommerce.mkt.posanhanguera.com.br"
  destinationPort: 80

namespace:
  istioInjection: true

opentelemetry:
  enabled: true
  type: nodejs
