fullnameOverride: ecommerce-frontend

image:
  repository: saiwmon/ecommerce-frontend
  tag: v1.0.0  # This will be updated by CI/CD
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"

env:
  NEXT_PUBLIC_CATALOG_SERVICE_URL: "http://ecommerce-catalog-service.ecommerce-catalog-service"
  NEXT_PUBLIC_ORDER_SERVICE_URL: "http://localhost:3002"
  OTEL_SERVICE_NAME: "ecommerce-frontend"
  NODE_ENV: "staging"

container:
  name: ecommerce-frontend
  port: 3000

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: alb

  commonAnnotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "60"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: "80"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb

  annotations:
    alb.ingress.kubernetes.io/group.name: staging-demo

  hosts:
    - host: staging.ecommerce.mkt.posanhanguera.com.br
      paths:
        - path: /
          pathType: Prefix

istio:
  enabled: false
  gateway: "istio-system/shared-gateway"
  host: "staging.ecommerce.mkt.posanhanguera.com.br"
  destinationPort: 80

namespace:
  istioInjection: false

opentelemetry:
  enabled: true
  type: nodejs
