apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cluster-dev
            url: https://kubernetes.default.svc
            namespace: bookinfo
            environment: dev
  template:
    metadata:
      name: "bookinfo-{{environment}}"
    spec:
      project: hands-on
      destination:
        namespace: "{{namespace}}"
        server: "{{url}}"
      
      source:
        repoURL: https://github.com/org-sam/infra-gitops
        targetRevision: HEAD
        path: apps/bookinfo/manifests
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
