apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        vpc_id: vpc-PLACEHOLDER # TODO: Replace with actual VPC ID
        revision: 1.16.0

  template:
    metadata:
      name: "aws-load-balancer-controller-{{name}}"
    spec:
      project: default

      source:
        repoURL: https://aws.github.io/eks-charts
        chart: aws-load-balancer-controller
        targetRevision: "{{revision}}"
        helm:
          valuesObject:
            clusterName: '{{name}}'
            serviceAccount:
              create: true
              name: aws-load-balancer-controller
            vpcId: '{{vpc_id}}'

      destination:
        server: "{{server}}"
        namespace: kube-system

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
