apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 1.1.0

  template:
    metadata:
      name: "external-secrets-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default

      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: "{{revision}}"
        helm:
          valuesObject:
            installCRDs: true
            serviceAccount:
              create: true
              name: external-secrets

      destination:
        server: "{{server}}"
        namespace: external-secrets

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
