apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 1.19.0
        hostedZoneId: Z0728988PJ08PEQVVTVX
        domainFilter: mkt.posanhanguera.com.br

  template:
    metadata:
      name: "external-dns-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: hands-on

      source:
        repoURL: https://kubernetes-sigs.github.io/external-dns
        chart: external-dns
        targetRevision: "{{revision}}"
        helm:
          valuesObject:
            provider:
              name: aws
            
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
            
            sources:
            - service
            - ingress
            - istio-gateway
            - istio-virtualservice
            
            policy: sync
            registry: txt
            txtOwnerId: "{{hostedZoneId}}"
            txtPrefix: "external-dns-"
            
            domainFilters:
            - "{{domainFilter}}"
            
            serviceAccount:
              create: true
              name: external-dns
            
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 50m
                memory: 64Mi

      destination:
        server: "{{server}}"
        namespace: external-dns

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
