apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  generators:
  - list:
      elements:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        version: 1.28.2
        component: ingressgateway
      - name: dev-demo
        server: https://kubernetes.default.svc
        version: 1.28.2
        component: egressgateway
  template:
    metadata:
      name: 'istio-{{component}}-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: hands-on
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: gateway
        targetRevision: '{{version}}'
        helm:
          valuesObject:
            service:
              type: LoadBalancer # Or NodePort/ClusterIP depending on env, but for demo usually LB is expected if on cloud
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
