apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            keda: "true"

  template:
    metadata:
      name: 'keda-{{name}}'
    spec:
      project: default
      
      source:
        repoURL: 'https://kedacore.github.io/charts'
        chart: keda
        targetRevision: '2.18.1'
        helm:
          valuesObject:
            resources:
              operator:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
              metricServer:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 50m
                  memory: 100Mi

      destination:
        server: '{{server}}'
        namespace: keda

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true