apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kiali
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        version: 2.20.0
  template:
    metadata:
      name: 'kiali-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "4"
    spec:
      project: hands-on
      source:
        repoURL: https://kiali.org/helm-charts
        chart: kiali-server
        targetRevision: '{{version}}'
        helm:
          valuesObject:
            auth:
              strategy: anonymous
            external_services:
              prometheus:
                url: "http://monitoring-base-{{name}}-k-prometheus.monitoring.svc:9090"
              grafana:
                enabled: true
                url: "http://monitoring-base-{{name}}-grafana.monitoring.svc:80"
              tracing:
                enabled: true
                provider: tempo
                tempo_config:
                  org_id: "1"
                  datasource_uid: "tempo"
                internal_url: "http://monitoring-tempo-{{name}}.monitoring.svc:3200"
                use_grpc: false
              istio:
                root_namespace: istio-system
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
