apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-otel-opr
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.102.0

  template:
    metadata:
      name: 'monitoring-otel-opr-{{name}}'
    spec:
      project: hands-on
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jsonPointers:
            - /webhooks/0/clientConfig/caBundle

      source:
        repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        chart: opentelemetry-operator
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            manager:
              collectorImage:
                repository: "otel/opentelemetry-collector-contrib"

            admissionWebhooks:
              certManager:
                enabled: false
              autoGenerateCert:
                enabled: true
              failurePolicy: Ignore

            admissionWebhooks:
              certManager:
                enabled: false
              autoGenerateCert:
                enabled: true
                recreate: true

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true