apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-otel-gateway
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.142.1

  template:
    metadata:
      name: 'monitoring-otel-gateway-{{name}}'
    spec:
      project: hands-on
      source:
        repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        chart: opentelemetry-collector
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            mode: deployment
            fullnameOverride: "otel-gateway"
            replicaCount: 1

            image:
              repository: "otel/opentelemetry-collector-contrib"

            presets:
              kubernetesAttributes:
                enabled: true

            resources:
              requests:
                memory: 2Gi
                cpu: 500m
              limits:
                memory: 4Gi
                cpu: 1000m

            config:
              receivers:
                otlp:
                  protocols:
                    grpc:
                      endpoint: ${env:MY_POD_IP}:4317
                    http:
                      endpoint: ${env:MY_POD_IP}:4318

              processors:
                batch: {}

                memory_limiter:
                  check_interval: 5s
                  limit_percentage: 80
                  spike_limit_percentage: 25

                resource:
                  attributes:
                    - key: loki.resource.labels
                      value: k8s.namespace.name, k8s.pod.name, k8s.container.name, k8s.node.name, k8s.deployment.name, k8s.statefulset.name, k8s.daemonset.name, service.name, service.namespace
                      action: insert

                transform:
                  log_statements:
                    - context: resource
                      statements:
                        - delete_key(attributes, "k8s.pod.uid")
                        - delete_key(attributes, "k8s.replicaset.uid")
                        - delete_key(attributes, "service.instance.id")
                        - delete_key(attributes, "observed_timestamp")
                        - delete_key(attributes, "k8s.pod.start_time")

                tail_sampling:
                  policies:
                    - name: errors
                      type: status_code
                      status_code:
                        status_codes: [ERROR]
                    - name: slow-traces
                      type: latency
                      latency:
                        threshold_ms: 1000
                    - name: probabilistic-sample
                      type: probabilistic
                      probabilistic:
                        sampling_percentage: 10

              exporters:
                otlphttp/loki:
                  endpoint: http://monitoring-loki-dev-demo.monitoring.svc:3100/otlp
                  tls:
                    insecure: true

                otlp/tempo:
                  endpoint: "monitoring-tempo-dev-demo.monitoring.svc:4317"
                  tls:
                    insecure: true

                prometheusremotewrite:
                  endpoint: http://monitoring-base-dev-demo-kube-prom-prometheus.monitoring.svc:9090/api/v1/write
                  resource_to_telemetry_conversion:
                    enabled: true
                  timeout: 30s
                  retry_on_failure:
                    enabled: true
                    initial_interval: 5s
                    max_interval: 30s
                    max_elapsed_time: 300s

              service:
                pipelines:
                  logs:
                    receivers: [otlp]
                    processors: [memory_limiter, resource, attributes, batch]
                    exporters: [otlphttp/loki]
                  metrics:
                    receivers: [otlp]
                    processors: [memory_limiter, k8sattributes, batch]
                    exporters: [prometheusremotewrite]
                  traces:
                    receivers: [otlp]
                    processors: [memory_limiter, k8sattributes, tail_sampling, batch]
                    exporters: [otlp/tempo]

            clusterRole:
              create: true

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
