apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-base
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 80.6.0

  template:
    metadata:
      name: 'monitoring-base-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: hands-on

      source:
        repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: kube-prometheus-stack
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            grafana:
              enabled: true
              adminPassword: "admin"
              forceDeployDatasources: true
              forceDeployDashboards: true              

              additionalDataSources:
                - name: Loki
                  type: loki
                  url: http://monitoring-loki-dev-demo-gateway.monitoring.svc:80
                  access: proxy
                  isDefault: false
                  jsonData:
                    maxLines: 1000
                    derivedFields:
                    - datasourceUid: tempo
                      matcherRegex: "traceID=(\\w+)"
                      name: TraceID
                      url: "$${__value.raw}"
                - name: Tempo
                  type: tempo
                  uid: tempo
                  url: http://monitoring-tempo-dev-demo.monitoring.svc:3200
                  access: proxy
                  isDefault: false
                  jsonData:
                    nodeGraph:
                      enabled: true
                    lokiSearch:
                      datasourceUid: Loki

            prometheus:
              enabled: true
              prometheusSpec:
                enableRemoteWriteReceiver: true
                retention: 10d
                storageSpec:
                  volumeClaimTemplate:
                    spec:
                      accessModes: ["ReadWriteOnce"]
                      resources:
                        requests:
                          storage: 10Gi
                resources:
                  requests:
                    memory: 400Mi
                  limits:
                    memory: 2Gi

            alertmanager:
              enabled: false

            nodeExporter:
              enabled: true
            kubeStateMetrics:
              enabled: true

      destination:
        server: '{{server}}'
        namespace: monitoring

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true