apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-otel-agent
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.142.1

  template:
    metadata:
      name: 'monitoring-otel-agent-{{name}}'
    spec:
      project: hands-on
      source:
        repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        chart: opentelemetry-collector
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            mode: daemonset
            fullnameOverride: "otel-agent"

            resources:
              requests:
                memory: 512Mi
                cpu: 200m
              limits:
                memory: 1Gi
                cpu: 500m

            image:
              repository: "otel/opentelemetry-collector-k8s"

            presets:
              logsCollection:
                enabled: true
                includeCollectorLogs: false
              kubernetesAttributes:
                enabled: true
              kubeletMetrics:
                enabled: false

            config:
              receivers:
                otlp:
                  protocols:
                    grpc:
                      endpoint: ${env:MY_POD_IP}:4317
                    http:
                      endpoint: ${env:MY_POD_IP}:4318

                hostmetrics:
                  root_path: /hostfs
                  collection_interval: 30s
                  scrapers:
                    cpu: {}
                    memory: {}
                    disk: {}
                    filesystem: {}
                    network: {}
                    load: {}

              processors:
                batch: {}
                memory_limiter:
                  check_interval: 5s
                  limit_percentage: 80
                  spike_limit_percentage: 25

              exporters:
                otlp:
                  endpoint: "otel-gateway.monitoring.svc:4317"
                  tls:
                    insecure: true

              service:
                pipelines:
                  logs:
                    receivers: [otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlp]
                  metrics:
                    receivers: [hostmetrics, otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlp]
                  traces:
                    receivers: [otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlp]

            extraVolumes:
              - name: hostfs
                hostPath:
                  path: /

            extraVolumeMounts:
              - name: hostfs
                mountPath: /hostfs
                readOnly: true
                mountPropagation: HostToContainer

            clusterRole:
              create: true

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
