apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-otel-agent
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.104.0

  template:
    metadata:
      name: 'monitoring-otel-agent-{{name}}'
    spec:
      project: hands-on
      source:
        repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        chart: opentelemetry-collector
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            mode: daemonset
            fullnameOverride: "otel-agent"

            image:
              repository: "otel/opentelemetry-collector-k8s"

            presets:
              logsCollection:
                enabled: true
                includeCollectorLogs: false
              kubernetesAttributes:
                enabled: true
              kubeletMetrics:
                enabled: false

            config:
              receivers:
                otlp:
                  protocols:
                    grpc:
                      endpoint: 0.0.0.0:4317
                    http:
                      endpoint: 0.0.0.0:4318

                filelog:
                  include:
                    - /var/log/pods/*/*/*.log
                  exclude:
                    - /var/log/pods/*/otc-container/*.log
                  start_at: end
                  include_file_path: true
                  include_file_name: false
                  operators:
                    - type: router
                      id: get-format
                      routes:
                        - output: parser-docker
                          expr: 'body matches "^\\{"'
                        - output: parser-crio
                          expr: 'body matches "^[^ Z]+ "'
                        - output: parser-containerd
                          expr: 'body matches "^[^ Z]+Z"'
                    - type: regex_parser
                      id: parser-crio
                      regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
                      output: extract_metadata_from_filepath
                      timestamp:
                        parse_from: attributes.time
                        layout_type: gotime
                        layout: '2006-01-02T15:04:05.999999999Z07:00'
                    - type: regex_parser
                      id: parser-containerd
                      regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
                      output: extract_metadata_from_filepath
                      timestamp:
                        parse_from: attributes.time
                        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                    - type: json_parser
                      id: parser-docker
                      output: extract_metadata_from_filepath
                      timestamp:
                        parse_from: attributes.time
                        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                    - type: regex_parser
                      id: extract_metadata_from_filepath
                      regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\/_]+)\/(?P<restart_count>\d+)\.log$'
                      parse_from: attributes["log.file.path"]
                    - type: move
                      from: attributes.log
                      to: body
                    - type: move
                      from: attributes.stream
                      to: attributes["log.iostream"]
                    - type: move
                      from: attributes.container_name
                      to: resource["k8s.container.name"]
                    - type: move
                      from: attributes.namespace
                      to: resource["k8s.namespace.name"]
                    - type: move
                      from: attributes.pod_name
                      to: resource["k8s.pod.name"]
                    - type: move
                      from: attributes.restart_count
                      to: resource["k8s.container.restart_count"]
                    - type: move
                      from: attributes.uid
                      to: resource["k8s.pod.uid"]

                kubeletstats:
                  collection_interval: 30s
                  auth_type: serviceAccount
                  endpoint: '${env:K8S_NODE_NAME}:10250'
                  insecure_skip_verify: true
                  metric_groups:
                    - node
                    - pod
                    - container
                  metrics:
                    container.cpu.utilization:
                      enabled: false
                    k8s.node.cpu.utilization:
                      enabled: false
                    k8s.pod.cpu.utilization:
                      enabled: false

                hostmetrics:
                  root_path: /hostfs
                  collection_interval: 30s
                  scrapers:
                    cpu: {}
                    memory: {}
                    disk: {}
                    filesystem: {}
                    network: {}
                    load: {}

                k8s_cluster:
                  auth_type: serviceAccount
                  node_conditions_to_report:
                    - Ready
                    - MemoryPressure
                    - DiskPressure
                  allocatable_types_to_report:
                    - cpu
                    - memory
                    - storage

              processors:
                batch:
                  timeout: 1s
                  send_batch_size: 1024
                memory_limiter:
                  limit_mib: 512
                  check_interval: 5s

              exporters:
                otlp:
                  endpoint: "otel-gateway.monitoring.svc:4317"
                  tls:
                    insecure: true

              service:
                pipelines:
                  logs:
                    receivers: [filelog, otlp]
                    processors: [memory_limiter, k8sattributes, batch]
                    exporters: [otlp]
                  metrics:
                    receivers: [hostmetrics, kubeletstats, k8s_cluster, otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlp]
                  traces:
                    receivers: [otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlp]

            extraVolumes:
              - name: hostfs
                hostPath:
                  path: /

            extraVolumeMounts:
              - name: hostfs
                mountPath: /hostfs
                readOnly: true
                mountPropagation: HostToContainer

            clusterRole:
              create: true
              rules:
              - apiGroups: [""]
                resources: ["pods", "namespaces", "nodes", "nodes/stats", "services", "endpoints", "replicationcontrollers", "resourcequotas"]
                verbs: ["get", "watch", "list"]
              - apiGroups: ["apps"]
                resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
                verbs: ["get", "watch", "list"]
              - apiGroups: ["batch"]
                resources: ["jobs", "cronjobs"]
                verbs: ["get", "watch", "list"]
              - apiGroups: ["autoscaling"]
                resources: ["horizontalpodautoscalers"]
                verbs: ["get", "watch", "list"]

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
