apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-loki
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 6.49.0

  template:
    metadata:
      name: 'monitoring-loki-{{name}}'
    spec:
      project: hands-on
      source:
        repoURL: 'https://grafana.github.io/helm-charts'
        chart: loki
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            deploymentMode: SingleBinary
            
            loki:
              auth_enabled: false
              commonConfig:
                replication_factor: 1
              storage:
                type: 'filesystem'
              schemaConfig:
                configs:
                  - from: "2024-01-01"
                    store: tsdb
                    object_store: filesystem
                    schema: v13
                    index:
                      prefix: index_
                      period: 24h

            singleBinary:
              replicas: 1
              persistence:
                enabled: true
                size: 10Gi
                # storageClassName: gp3
            
            gateway:
              enabled: true
              service:
                type: ClusterIP

            backend:
              replicas: 0
            read:
              replicas: 0
            write:
              replicas: 0

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true