apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-otel-collector
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.142.1

  template:
    metadata:
      name: 'monitoring-otel-collector-{{name}}'
    spec:
      project: hands-on
      source:
        repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        chart: opentelemetry-collector
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            mode: deployment

            config:
              receivers:
                otlp:
                  protocols:
                    grpc:
                      endpoint: 0.0.0.0:4317
                    http:
                      endpoint: 0.0.0.0:4318

              processors:
                batch:
                  timeout: 1s
                  send_batch_size: 1024

              exporters:
                otlp:
                  endpoint: "monitoring-tempo-dev-demo.monitoring.svc:4317"
                  tls:
                    insecure: true

              service:
                pipelines:
                  traces:
                    receivers: [otlp]
                    processors: [batch]
                    exporters: [otlp]

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true