apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: signoz-agent
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.15.0 

  template:
    metadata:
      name: 'signoz-agent-{{name}}'
    spec:
      project: hands-on

      source:
        repoURL: 'https://charts.signoz.io'
        chart: k8s-infra
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            otelCollectorEndpoint: signoz-dev-demo-otel-collector.signoz.svc.cluster.local:4317
            otelCollectorProtocol: grpc
            
            # Habilita a coleta de tudo em um único agente
            metrics:
              enabled: true
            logs:
              enabled: true
            traces:
              enabled: true

            global:
              clusterName: "dev-demo"

      destination:
        server: '{{server}}'
        namespace: signoz

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true