apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: signoz
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.105.2 

  template:
    metadata:
      name: 'signoz-{{name}}'
    spec:
      project: hands-on

      source:
        repoURL: 'https://charts.signoz.io'
        chart: signoz
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            global:
              storageClass: gp3

            clickhouse:
              installCustomStorageClass: true

      destination:
        server: '{{server}}'
        namespace: signoz

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true