apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: springboot-demo
  namespace: springboot-demo
spec:
  exporter:
    endpoint: http://otel-collector.monitoring.svc:4317
  
  propagators:
    - tracecontext
    - baggage
  
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"

  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.33.6
    env:
      # Habilitar logs de debug para troubleshooting
      - name: OTEL_JAVAAGENT_DEBUG
        value: "false"
