apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: production
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istio-{{cluster}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: hands-on
      sources:
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: base
          targetRevision: 1.28.2
          helm:
            releaseName: istio-base
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: istiod
          targetRevision: 1.28.2
          helm:
            releaseName: istiod
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: gateway
          targetRevision: 1.28.2
          helm:
            releaseName: istio-ingressgateway
            valuesObject:
              service:
                type: ClusterIP
              labels:
                istio: ingressgateway
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
