apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev-demo
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istio-base-{{cluster}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: hands-on
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base
        targetRevision: 1.28.2
        helm:
          releaseName: istio-base
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev-demo
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istiod-{{cluster}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: hands-on
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: istiod
        targetRevision: 1.28.2
        helm:
          releaseName: istiod
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev-demo
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: 'istio-ingressgateway-{{cluster}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: hands-on
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: gateway
        targetRevision: 1.28.2
        helm:
          releaseName: istio-ingressgateway
          valuesObject:
            service:
              type: ClusterIP
            labels:
              istio: ingressgateway
      destination:
        server: '{{server}}'
        namespace: istio-ingress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
