apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-otel-collector
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-demo
        server: https://kubernetes.default.svc
        revision: 0.104.0

  template:
    metadata:
      name: 'monitoring-otel-collector-{{name}}'
    spec:
      project: hands-on
      source:
        repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        chart: opentelemetry-collector
        targetRevision: '{{revision}}'
        helm:
          valuesObject:
            mode: deployment
            fullnameOverride: "otel-collector"

            image:
              repository: "otel/opentelemetry-collector-contrib"
              tag: "0.104.0"

            config:
              receivers:
                otlp:
                  protocols:
                    grpc:
                      endpoint: 0.0.0.0:4317
                    http:
                      endpoint: 0.0.0.0:4318

              processors:
                batch:
                  timeout: 1s
                  send_batch_size: 1024
                k8sattributes:
                  auth_type: "serviceAccount"
                  passthrough: false
                  extract:
                    metadata:
                      - k8s.pod.name
                      - k8s.pod.uid
                      - k8s.deployment.name
                      - k8s.namespace.name
                      - k8s.container.name
                    labels:
                      - tag_name: app
                        key: app
                        from: pod

              exporters:
                otlp:
                  endpoint: "monitoring-tempo-dev-demo.monitoring.svc:4317"
                  tls:
                    insecure: true

                debug:
                  verbosity: detailed

              service:
                pipelines:
                  traces:
                    receivers: [otlp]
                    processors: [k8sattributes, batch]
                    exporters: [otlp, debug]

            clusterRole:
              create: true
              rules:
              - apiGroups: [""]
                resources: ["pods", "namespaces", "nodes"]
                verbs: ["get", "watch", "list"]
              - apiGroups: ["apps"]
                resources: ["replicasets", "deployments", "statefulsets"]
                verbs: ["get", "watch", "list"]

      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true