apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecommerce-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cluster-dev
            url: https://kubernetes.default.svc
            namespace: ecommerce-frontend
            path: apps/environments/dev/ecommerce-frontend
            environment: dev
  template:
      metadata:
        name: "{{namespace}}-{{environment}}"
      spec:
        project: default
        source:
          path: "{{path}}"
          repoURL: https://github.com/org-sam/infra-gitops
          targetRevision: HEAD
        destination:
          namespace: "{{namespace}}"
          server: "{{url}}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true